### ISSUE TITLE
Generic vs. theme-specific rules (for which themes?)

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/2017.2#25]
Should we focus on generic rules (for all/most INSPIRE themes) or specific ones (for one or a small number of themes)? 

If the latter, which themes/use cases should be used to prototype and test the simplification rules / GeoJSON encoding rule?

**Comment by cportele** [comment]
In general, a proliferation of encoding rules on a theme- or feature-type-basis may create new issues, so that should probably be avoided unless there are good reasons. 

On the other hand, I would recommend to validate that the encoding of a feature type meets the intended goals through implementation before considering that encoding a Good Practice. If the existing, encoding rule could be improved for a feature type by adding specific conversion rules, this should be done and the encoding rule should be amended.

That is, develop the encoding rule and the encodings incrementally.

**Comment by michellutz** [comment]
[2017.2 meeting 2018-09-28]
- The main question here is whether the action should aim for generic or theme-specific rules?
- It was agreed that the action should develop a list of generic simplification rules that can be applied to create an encoding as well as a default (sub-)set of these rules that should be applied to all themes (wherever possible). Additional further rules from the list might then be applied in addition for specific themes.
- In general, the set of rules applied for a given theme and/or use case need to be validated before promoting them as a good pratice in INSPIRE.
- Use issue #31 to propose sample INSPIRE data sets, themes and/or use cases that can be used to develop examples of the proposed GeoJSON encoding and simplification rules. These examples should serve to prototype and test the proposed approaches, to focus our discussion and to illustrate the proposed approaches in the GP documents. Where possible, please also include (pointers to) open sample data that can be re-used.

**Comment by nmtoken** [comment]
Ideally we want generic rules, but some rules might not apply to data in all themes, just because of the nature of the data.
