### ISSUE TITLE
Definition of  flattening - denormalisation

### ISSUE THREAD

**Issue by PalmJanssen** [INSPIRE-MIF/2017.2#29]
Related to the concept of flattening data structure.

We must come up with a proper (working) definition of what we mean by flattening of data structures. I suppose this can be found somewhere already or the editor can take care of it.

We usually take the different levels of simple features as levels of complexity. SF0 being the one that usually is the intended goal of a flattened data structure.

**Comment by heidivanparys** [comment]
Maybe the following concepts could be helpful?

![concept model](https://user-images.githubusercontent.com/11427611/48206069-7477a400-e365-11e8-9396-cb1f4dd4560c.png)

**data structure**
physical or logical relationship among units of data and the data themselves
[ISO/IEC 2382:2015, 2122353]

**flat data structure**
data structure in which records have no structured interrelationship
NOTE This requires that an application knows how the data are organized within the data structure.
[FEDERAL HIGHWAY ADMINISTRATION. _Data Integration Glossary_ [online]. 2001. Available from: [https://www.fhwa.dot.gov/infrastructure/asstmgmt/010394.pdf](https://www.fhwa.dot.gov/infrastructure/asstmgmt/010394.pdf)]

**tree**
tree data structure, hierarchical data structure
data structure containing nodes that are linked together hierarchically with at most one parent node for
each node, and with only one root node
[ISO/IEC 2382:2015, 2121633]

**network structure**
network data structure
data structure that arranges entities or attributes as nodes and that, in contrast to a tree structure, permits nodes to have multiple parent nodes
[ISO/IEC 2382:2015, 2121486]

**relational structure**
relational data structure
data structure in which the data are arranged as relations
[ISO/IEC 2382:2015, 2121468]

**record**
&lt;organization of data&gt; set of data elements treated as a unit
[ISO/IEC 2382:2015, 2121601]

**data element**
&lt;organization of data&gt; unit of data that is considered in context to be indivisible
[ISO/IEC 2382:2015, 2121599]

**relation**
set of entity occurrences that have the same attributes, together with these attributes
[ISO/IEC 2382:2015, 2121466]

Examples of flat data structure:
-    XML with no XLinks and two levels in the tree (feature: 1st level, feature attributes: 2nd level)
-    Shapefile
-    CSV
-    data in relational database without foreign keys

Examples of tree data structure:
-    XML with more than two levels in the tree (e.g. INSPIRE)

Examples of relation structure:
-    data in relational database with foreign keys

**Question:**
How about multiplicity > 1? Is that by definition not flat?


I am not sure that using the concept normalization is a good idea, as it is used typically in connection to relational databases as far as I know:

**normalization**
&lt;relational database&gt; process of transforming a relation into one or more simpler relations free of attribute redundancies or inconsistencies in order to support referential integrity
[ISO/IEC 20944-1:2013, 3.14.4.12]

**Comment by heidivanparys** [comment]
For clarity, I copy here an extract of 
[1] FEDERAL HIGHWAY ADMINISTRATION. _Data Integration Primer_ [online]. August 2010. Available from: https://www.fhwa.dot.gov/asset/dataintegration/if10019/if10019.pdf

I found this document in the search for a definiton of "flattening" and "flat model". I think it could be useful, especially if we can strengthen the definitions so they fit with the ISO and other relevant standards in this area, f.eks. [ISO/IEC 2382:2015](https://www.iso.org/obp/ui/#iso:std:iso-iec:2382:ed-1:v1:en).

Hierarchical data structure, network data structure and relational data structure are available in ISO/IEC 2382:2015 as mentioned above. Flat data structure is not, so we may have to define that concept further, and, if needed, introduce additional concepts if it turns out that we can define possible categories of "flat data structures".

![billede](https://user-images.githubusercontent.com/11427611/48248988-666f6500-e3f1-11e8-92a3-66a50e827bc4.png)
