### ISSUE TITLE
Terms: Profile, Extension and Flattening

### ISSUE THREAD

**Issue by PalmJanssen** [INSPIRE-MIF/2017.2#32]
**Glossary proposal**

Add one or several proposals for terms and their definitions

# Profile
In the context of application schema: Subset of the complete functionality and information content of an application schema.

# Extension
In the context of application schema: Adding semantics and or functionality to an existing application schema.

# Flattening
Simplifying a complex Application Schema model, up to the point where all complex data structures have been resolved to feature type properties whose type is either a simple type (like Integer, Boolean or CharacterString), a code list, or an enumeration. (note: the issue of multiple or singular attributes is not specifically included).  
(Inspired on ShapeChange text)

**Comment by heidivanparys** [comment]
I think we should try to avoid using the same terms for different meanings when a term is defined already in ISO 19100.

**Profile**

I had a look again at how "profile" is defined in ISO 19106 (which is taken/modified from ISO/IEC TR 10000-1).

In the document mentioned in #28 , it is written that "According to ISO 19106, a profile is a set of one or more base standards or subsets of base standards, and, where applicable, the identification of chosen clauses, classes, options and parameters of those base standards, that are necessary for accomplishing a
particular function ([3]). Thus, a profile of the INSPIRE data model is a subset of the INSPIRE data model.". 

However, when thinking about it again and reading ISO 19106 again, this seems to be wrong. A profile is a set of one or more base **standards** or subsets of base standards. A a subset of the INSPIRE data model is, well, just a subset of the INSPIRE data model :-). A profile could e.g. be a European standard, that among other things, would include a subset of the INSPIRE data model. Do you agree?

@cportele I am wondering why it is called profiling in ShapeChange? Is a possible explanation that usually, a subset of a data model is created for the purpose of inclusion in a standard, which is a profile of another standard? Or another reason?

**Extension**

The term "extension" is used a lot in ISO 19106, unfortunately without with a clear definition. The meaning seems to be rather broad though as the following is also described as being extensions:

- defining a more stringent code list
- applying a more stringent obligation to an element (e.g. mandatory instead of conditional)
- replacing a free text element by an enumerated list

So what some would call a restriction is also considered as an extension. Should we maybe operate with something like the following?

<img src="https://user-images.githubusercontent.com/11427611/48250584-bdc40400-e3f6-11e8-8757-154c49938bb1.png" width="50%" alt="extension">

**Flattening**

Maybe the following could be useful? If "data structure" is a kind of "form of data"?

**transform**
change the form of data according to specified rules, without fundamentally changing the meaning of the data
[ISO/IEC 2382:2015, 2122172]

**flatten**
transform to a flat data structure (#29)

I didn't think it completely through though. Should we distinguish between a application schema and the data itself? Or could an application schema be treated as data as well, data about data?

**Comment by heidivanparys** [comment]
[Summary of meeting 2018-11-09]

Look up if and how other standards bodies define" profile".

A possible solution may be to define the term profile more broader than is currently done in ISO.

E.g.:
- profile = (to be defined, something with a subset probably, and a particular function)
- (base) standards profile = set of one or more base standards or subsets of base standards, and, where applicable, the identification of chosen clauses, classes, options and parameters of those base standards, that are necessary for accomplishing a particular function
- application schema profile = ...
- ...

Regarding extension: similar discussion, there seems to consensus regarding what a "data model extension" is. So "extension" is broader than that, something with additional requirements.

**Comment by cportele** [comment]
There have been long discussions in the OGC Architecture Board about "profile" etc. I will check the results and get back.

**Comment by heidivanparys** [comment]
Regarding profile: this may help too, a brand new document, with input from OGC it seems as one from the editors is from OGC:

CAR, Nicholas. _Profile Guidance_ [online]. 29 November 2018. W3C. Available from: https://w3c.github.io/dxwg/profiles/

**Comment by cportele** [comment]
I had a look at the result of the OGC discussions this year (they were presented in September at the Stuttgart TC meeting). As a standards organisation OGC is mainly looking at profiles of their standards/specs. 

The terms and definitions are:

> A **profile** is a pure subset of an existing standard including restrictions on or deletions of conformance clauses related to the sub-setting.

This is a Type 1 Profile in ISO 19106:2004.

And:

> An **extension** is a set of one or more conformance clauses that defines new options for an existing standard. Extensions are generally designed to add additional capabilities that are not part of the core standard.

> A **profile with extension** is a set of one or more conformance clauses from a base standard that includes at least one new conformance clause (extension).

**Comment by cportele** [comment]
There is now a first Public Working Draft available on the W3C Profile Ontology:

https://www.w3.org/TR/2018/WD-dx-prof-20181218/
